import 'package:umte_project/database/database.dart';

import '../data/enums/unit.dart';

List<Food> getFoodsData() {
  return const [
    Food(id: 1, name: 'Banana', description: "banana, fruit of the genus Musa, of the family Musaceae, one of the most important fruit crops of the world. The banana is grown in the tropics, and, though it is most widely consumed in those regions, it is valued worldwide for its flavour, nutritional value, and availability throughout the year. Cavendish, or dessert, bananas are most commonly eaten fresh, though they may be fried or mashed and chilled in pies or puddings. They may also be used to flavour muffins, cakes, or breads. Cooking varieties, or plantains, are starchy rather than sweet and are grown extensively as a staple food source in tropical regions; they are cooked when ripe or immature. A ripe fruit contains as much as 22 percent of carbohydrate and is high in dietary fibre, potassium, manganese, and vitamins B6 and C.", calories: 0.940268928, fibre: 0.012, carbohydrates: 0.22, sugars: 0.19, fats: 0.002, unit: Unit.grams),
    Food(id: 2, name: 'Strawberries', description: "strawberry, (genus Fragaria), genus of more than 20 species of flowering plants in the rose family (Rosaceae) and their edible fruit. Strawberries are native to the temperate regions of the Northern Hemisphere, and cultivated varieties are widely grown throughout the world. The fruits are rich in vitamin C and are commonly eaten fresh as a dessert fruit, are used as a pastry or pie filling, and may be preserved in many ways. Strawberry shortcake—made of fresh strawberries, sponge cake, and whipped cream—is a traditional American dessert.", calories: 0.34, fibre: 0.79, carbohydrates: 6.16, sugars: 4.29, fats: 0.37, unit: Unit.grams),
    Food(id: 3, name: 'Chia seeds', description: "chia, (Salvia hispanica), also called Mexican chia or salba chia, species of flowering plant in the mint family (Lamiaceae), grown for its edible seeds. The plant is native to Mexico and Guatemala, where it was an important crop for pre-Columbian Aztecs and other Mesoamerican Indian cultures. Chia seeds are touted for their health benefits, being high in fibre and omega-3 fatty acids, and are now grown commercially in several countries, including Argentina, Australia, Bolivia, Peru, and the United States.", calories: 4.95, fibre: 0.212, carbohydrates: 0.2, sugars: 0.04, fats: 0.31, unit: Unit.grams),
    Food(id: 4, name: 'Oatmeal', description: "chia, (Salvia hispanica), also called Mexican chia or salba chia, species of flowering plant in the mint family (Lamiaceae), grown for its edible seeds. The plant is native to Mexico and Guatemala, where it was an important crop for pre-Columbian Aztecs and other Mesoamerican Indian cultures. Chia seeds are touted for their health benefits, being high in fibre and omega-3 fatty acids, and are now grown commercially in several countries, including Argentina, Australia, Bolivia, Peru, and the United States.", calories: 4.0, fibre: 0.07, carbohydrates: 0.68, sugars: 0.02, fats: 0.07, unit: Unit.grams),
    Food(id: 6, name: 'Red apple', description: "Jablko červené obsahuje řadu vitamínů, zejména vitamín C, a důležitou vlákninu. Nabízí nám také řadu minerálních látek a stopových prvků (draslík, hořčík, vápník, železo, fosfor, mangan).", calories: 0.73, fibre: 0.02, carbohydrates: 0.17, sugars: 0.12, fats: 0.0, unit: Unit.grams),
    Food(id: 7, name: 'Milk', description: "chia, (Salvia hispanica), also called Mexican chia or salba chia, species of flowering plant in the mint family (Lamiaceae), grown for its edible seeds. The plant is native to Mexico and Guatemala, where it was an important crop for pre-Columbian Aztecs and other Mesoamerican Indian cultures. Chia seeds are touted for their health benefits, being high in fibre and omega-3 fatty acids, and are now grown commercially in several countries, including Argentina, Australia, Bolivia, Peru, and the United States.", calories: 0.47, fibre: null, carbohydrates: 0.17, sugars: 0.12, fats: 0.0, unit: Unit.millilitre),
    Food(id: 8, name: 'Milk Chocolate (Milka)', description: "Milka chocolate milk (Alpine milk) contains cocoa butter, cocoa mass, sugar, skimmed milk powder, soy lecithin and vanilla aroma.", calories: 0.528528, fibre: 0.018, carbohydrates: 0.59, sugars: 0.59, fats: 0.29, unit: Unit.grams),
  ];
}