// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVOpQnaOM8LE8V-N9urv5J99DO9pNr15E',
    appId: '1:903869084397:web:211f1554517f680f83d2e4',
    messagingSenderId: '903869084397',
    projectId: 'umteproject',
    authDomain: 'umteproject.firebaseapp.com',
    storageBucket: 'umteproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHTAjjuMxQnvTJMgNSp4HB8Fvhy-zzJac',
    appId: '1:903869084397:android:8c82973718691d4c83d2e4',
    messagingSenderId: '903869084397',
    projectId: 'umteproject',
    storageBucket: 'umteproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZYvy2EIT2cqjblHJOSafMKsEXQhdlWU',
    appId: '1:903869084397:ios:2c419eff18586d3983d2e4',
    messagingSenderId: '903869084397',
    projectId: 'umteproject',
    storageBucket: 'umteproject.appspot.com',
    iosClientId: '903869084397-q4v2dubc9sp6prnr20cfai7c2to5jn8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.umteProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWZYvy2EIT2cqjblHJOSafMKsEXQhdlWU',
    appId: '1:903869084397:ios:2c419eff18586d3983d2e4',
    messagingSenderId: '903869084397',
    projectId: 'umteproject',
    storageBucket: 'umteproject.appspot.com',
    iosClientId: '903869084397-q4v2dubc9sp6prnr20cfai7c2to5jn8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.umteProject',
  );
}
